version: "3.7"
services:
  backend:
    container_name: backend
    image: docker.io/desoprotocol/backend:latest
    command: run
    restart: on-failure
    volumes:
    - db:/db
    ports:
    - 17001:17001
    - 17000:17000
    env_file:
    - dev.env
    expose:
    - "17001"
    - "17000"
  frontend:
    container_name: frontend 
    image: docker.io/desoprotocol/frontend:latest
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    env_file:
    - dev.env
    expose:
    - "8080"
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
      - ./certs/conf:/etc/letsencrypt
      - ./certs/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certs/conf:/etc/letsencrypt
      - ./certs/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  db:
